"""rich_resources_and_user_resources

Revision ID: 321862e89b84
Revises: db6b859ccb2d
Create Date: 2026-07-20 14:43:41.205060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321862e89b84'
down_revision: Union[str, None] = 'db6b859ccb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_resources',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('watch_progress_seconds', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_user_resources_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_resources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_resources')),
    sa.UniqueConstraint('user_id', 'resource_id', name=op.f('uq_user_resources_user_id'))
    )
    op.create_index(op.f('ix_user_resources_resource_id'), 'user_resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_resources_user_id'), 'user_resources', ['user_id'], unique=False)
    op.add_column('resources', sa.Column('category', sa.Enum('BEST_PLAYLIST', 'BEST_SINGLE_VIDEO', 'NPTEL', 'IIT_LECTURE', 'MIT_OCW', 'STANFORD', 'HARVARD', 'COURSERA', 'EDX', 'DOCUMENTATION', 'REFERENCE_BOOK', 'PRACTICE_WEBSITE', 'PYQ_EXPLANATION', 'CHEAT_SHEET', 'FORMULA_NOTES', 'GITHUB', 'VISUALIZATION', 'RESEARCH_PAPER', 'OTHER', name='resourcecategory', native_enum=False, length=32), nullable=True))
    op.add_column('resources', sa.Column('ranking', sa.Enum('GOLD', 'SILVER', 'BRONZE', name='resourcerank', native_enum=False, length=32), nullable=True))
    op.add_column('resources', sa.Column('instructor', sa.String(length=255), nullable=True))
    op.add_column('resources', sa.Column('channel', sa.String(length=255), nullable=True))
    op.add_column('resources', sa.Column('organization', sa.String(length=255), nullable=True))
    op.add_column('resources', sa.Column('language', sa.String(length=64), nullable=False, server_default="'English'"))
    op.add_column('resources', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('resources', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('resources', sa.Column('why_recommended', sa.Text(), nullable=True))
    op.add_column('resources', sa.Column('thumbnail_url', sa.String(length=1024), nullable=True))
    op.add_column('resources', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('resources', sa.Column('last_verified', sa.Date(), nullable=True))
    op.add_column('resources', sa.Column('needs_review', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('resources', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('resources', sa.Column('is_obsolete', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'is_obsolete')
    op.drop_column('resources', 'is_approved')
    op.drop_column('resources', 'needs_review')
    op.drop_column('resources', 'last_verified')
    op.drop_column('resources', 'confidence_score')
    op.drop_column('resources', 'thumbnail_url')
    op.drop_column('resources', 'why_recommended')
    op.drop_column('resources', 'rating')
    op.drop_column('resources', 'year')
    op.drop_column('resources', 'language')
    op.drop_column('resources', 'organization')
    op.drop_column('resources', 'channel')
    op.drop_column('resources', 'instructor')
    op.drop_column('resources', 'ranking')
    op.drop_column('resources', 'category')
    op.drop_index(op.f('ix_user_resources_user_id'), table_name='user_resources')
    op.drop_index(op.f('ix_user_resources_resource_id'), table_name='user_resources')
    op.drop_table('user_resources')
    # ### end Alembic commands ###
