"""study_session_focus_fields

Revision ID: db6b859ccb2d
Revises: 500dd9cec4a9
Create Date: 2026-07-20 12:46:15.728264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6b859ccb2d'
down_revision: Union[str, None] = '500dd9cec4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'study_sessions',
        sa.Column('interruptions', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('study_sessions', sa.Column('focus_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'focus_score')
    op.drop_column('study_sessions', 'interruptions')
    # ### end Alembic commands ###
